### ISSUE TITLE
Setting up AccuweatherAPI 

### ISSUE THREAD

**Issue by emilyyankan** [NittanyLions42/Viltvodle-VI#10]
## Task description
Setting up AccuweatherAPI 

## Detailed Steps
- [x] Create an account in [AccuweatherAPI](https://www.accuweather.com/)
- [x] Obtain a personal API Key
- [x] Add `Okhttp` dependencies for networking and `moshi` JSON Parsing in `buildgardle`

## Relate to issue(s)

/relate subtask-of [#9](https://github.com/NittanyLions42/Viltvodle-VI/issues/9)
Fixes {link for the pull request}
