### ISSUE TITLE
[Epic]: Setting Up Room Database 

### ISSUE THREAD

**Issue by emilyyankan** [NittanyLions42/Viltvodle-VI#2]
## Summary
Setting up a Room database for the Wellness Buddy android app.

## Design documents/references

- [ ]  [Update gradle dependencies to import Room Library](https://github.com/NittanyLions42/Viltvodle-VI/issues/3)
- [ ]  Update Entity-Relationship diagram

### Model
---
This package includes all data classes that represent the tables in the database.
- [ ]  Create the Entity package, set up entities and Data Access Objects (DAOs) 

### Controller
---
This package is responsible for handling business logic and interacting with the model. 
- [ ]  DB interface with CRUD operations
- [ ]  DB instance, create abstract `RoomDatabase` class

### Views
---
This package is responsible for rendering UI elements and listening to user actions.
- [ ]  Initialize Database in `Application` class
