### ISSUE TITLE
Update gradle dependencies to import Room Library

### ISSUE THREAD

**Issue by emilyyankan** [NittanyLions42/Viltvodle-VI#3]
## Task description
Update gradle dependencies to import Room Library
Ref : https://developer.android.com/training/data-storage/room

## Detailed Steps
- [ ] Add room library into `build.gradle`
- [ ] Validate dependencies are added successfully
- [ ] Push commit to repo

## Relate to issue(s)

/relate subtask-of [Setting Up Room Database #2](https://github.com/NittanyLions42/Viltvodle-VI/issues/2)
Fixes {link for the pull request}
